### ISSUE TITLE
WANTED: Missing jokes, DEAD OR ALIVE

### ISSUE THREAD

**Issue by bartosz-zbik** [KMPSUJ/wkurwiacz#1]
Just add those missing ones.

**Comment by bartosz-zbik** [comment]
Jokes which I remember, but are currently not present:
 - 'Po co Prezes idzie do lasu? Polisa.'

And one new wich comes from some commercial I heard recently:
- 'Jaki jest najlepszy owoc po imprezie? Pomelo.'

**Comment by falcotinnunculus** [comment]
done
